/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VelasIndexRouteImport } from './routes/velas.index'
import { Route as VelasSlugRouteImport } from './routes/velas.$slug'
import { Route as PedidoPendenteRouteImport } from './routes/pedido.pendente'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as HomenagemIdRouteImport } from './routes/homenagem.$id'
import { Route as AuthenticatedMeusPedidosRouteImport } from './routes/_authenticated/meus-pedidos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVelasRouteImport } from './routes/_authenticated/admin.velas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminHomenagensRouteImport } from './routes/_authenticated/admin.homenagens'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VelasIndexRoute = VelasIndexRouteImport.update({
  id: '/velas/',
  path: '/velas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VelasSlugRoute = VelasSlugRouteImport.update({
  id: '/velas/$slug',
  path: '/velas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoPendenteRoute = PedidoPendenteRouteImport.update({
  id: '/pedido/pendente',
  path: '/pedido/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomenagemIdRoute = HomenagemIdRouteImport.update({
  id: '/homenagem/$id',
  path: '/homenagem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusPedidosRoute =
  AuthenticatedMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVelasRoute = AuthenticatedAdminVelasRouteImport.update({
  id: '/velas',
  path: '/velas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomenagensRoute =
  AuthenticatedAdminHomenagensRouteImport.update({
    id: '/homenagens',
    path: '/homenagens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/homenagem/$id': typeof HomenagemIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/velas/$slug': typeof VelasSlugRoute
  '/velas/': typeof VelasIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/homenagens': typeof AuthenticatedAdminHomenagensRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/velas': typeof AuthenticatedAdminVelasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/homenagem/$id': typeof HomenagemIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/velas/$slug': typeof VelasSlugRoute
  '/velas': typeof VelasIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/homenagens': typeof AuthenticatedAdminHomenagensRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/velas': typeof AuthenticatedAdminVelasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/homenagem/$id': typeof HomenagemIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/velas/$slug': typeof VelasSlugRoute
  '/velas/': typeof VelasIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/homenagens': typeof AuthenticatedAdminHomenagensRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/velas': typeof AuthenticatedAdminVelasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/admin'
    | '/meus-pedidos'
    | '/homenagem/$id'
    | '/pedido/$id'
    | '/pedido/pendente'
    | '/velas/$slug'
    | '/velas/'
    | '/admin/configuracoes'
    | '/admin/homenagens'
    | '/admin/pedidos'
    | '/admin/usuarios'
    | '/admin/velas'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/meus-pedidos'
    | '/homenagem/$id'
    | '/pedido/$id'
    | '/pedido/pendente'
    | '/velas/$slug'
    | '/velas'
    | '/admin/configuracoes'
    | '/admin/homenagens'
    | '/admin/pedidos'
    | '/admin/usuarios'
    | '/admin/velas'
    | '/admin'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-funciona'
    | '/_authenticated/admin'
    | '/_authenticated/meus-pedidos'
    | '/homenagem/$id'
    | '/pedido/$id'
    | '/pedido/pendente'
    | '/velas/$slug'
    | '/velas/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/homenagens'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/velas'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  HomenagemIdRoute: typeof HomenagemIdRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PedidoPendenteRoute: typeof PedidoPendenteRoute
  VelasSlugRoute: typeof VelasSlugRoute
  VelasIndexRoute: typeof VelasIndexRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velas/': {
      id: '/velas/'
      path: '/velas'
      fullPath: '/velas/'
      preLoaderRoute: typeof VelasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velas/$slug': {
      id: '/velas/$slug'
      path: '/velas/$slug'
      fullPath: '/velas/$slug'
      preLoaderRoute: typeof VelasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/pendente': {
      id: '/pedido/pendente'
      path: '/pedido/pendente'
      fullPath: '/pedido/pendente'
      preLoaderRoute: typeof PedidoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homenagem/$id': {
      id: '/homenagem/$id'
      path: '/homenagem/$id'
      fullPath: '/homenagem/$id'
      preLoaderRoute: typeof HomenagemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-pedidos': {
      id: '/_authenticated/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/velas': {
      id: '/_authenticated/admin/velas'
      path: '/velas'
      fullPath: '/admin/velas'
      preLoaderRoute: typeof AuthenticatedAdminVelasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homenagens': {
      id: '/_authenticated/admin/homenagens'
      path: '/homenagens'
      fullPath: '/admin/homenagens'
      preLoaderRoute: typeof AuthenticatedAdminHomenagensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminHomenagensRoute: typeof AuthenticatedAdminHomenagensRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVelasRoute: typeof AuthenticatedAdminVelasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminHomenagensRoute: AuthenticatedAdminHomenagensRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVelasRoute: AuthenticatedAdminVelasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMeusPedidosRoute: typeof AuthenticatedMeusPedidosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMeusPedidosRoute: AuthenticatedMeusPedidosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  HomenagemIdRoute: HomenagemIdRoute,
  PedidoIdRoute: PedidoIdRoute,
  PedidoPendenteRoute: PedidoPendenteRoute,
  VelasSlugRoute: VelasSlugRoute,
  VelasIndexRoute: VelasIndexRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
